services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    ContaoGraveyard\StylePickerBundle\:
        resource: '../src/'
        #exclude: '../src/{Model}'
